version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  demo:
    build:
      context: .
      dockerfile: Dockerfile.demo
    ports:
      - "8001:8000"
