version: '2'

services:
  web:
    image: golang:1.11-alpine
    ports:
      - "80:8080"
    command: go run hello.go
    working_dir: /app
    volumes:
      - .:/app
      - $GOPATH:/go
    environment:
      - GIN_MODE=debug
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: fluentd:24224
        tag: httpd.access

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    logging:
        driver: "json-file"
        options:
            max-size: 100m
            max-file: "5"

  elasticsearch:
    image: elasticsearch

  kibana:
    image: kibana
    ports:
      - 5601:5601