version: '2'

services:
  web:
    image: golang:1.11-alpine
    hostname: web
    ports:
      - "80:8080"
    command: go run hello.go
    working_dir: /app
    volumes:
      - .:/app
      - $GOPATH:/go
    environment:
      - GIN_MODE=debug
    logging:
      driver: json-file
      options:
        env: ${ENV}
        labels: demo_web

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.4.2
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers

  elasticsearch:
    image: elasticsearch

  kibana:
    image: kibana
    ports:
      - 5601:5601
