version: '3'

services:
  registry:
    image: registry:2.6.2
    ports:
      - "5000:5000"
    volumes:
      - ./registry/lib:/var/lib/registry
      - ./registry/etc:/etc/docker/registry

  my-image:
    build: .
    image: 127.0.0.1:5000/gopro-image-test:alpine
