################################################################
# Service Provider
################################################################

defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "http://whoami:80"
    weight = 9
  [backends.backend2]
    [backends.backend2.servers.server1]
    url = "http://whoami2:80"
    weight = 2

[frontends]
  [frontends.frontend1]
  backend = "backend1"
    [frontends.frontend1.routes.test_1]
    rule = "Host:demo1"
  [frontends.frontend2]
  backend = "backend2"
    [frontends.frontend2.routes.test_1]
    rule = "Host:demo2"

################################################################
# Docker Provider
################################################################

# # Enable Docker Provider.
# [docker]

# # Docker server endpoint. Can be a tcp or a unix socket endpoint.
# #
# # Required
# #
# endpoint = "unix:///var/run/docker.sock"

# # Default domain used.
# # Can be overridden by setting the "traefik.domain" label on a container.
# #
# # Required
# #
# domain = "zzz"

# # Enable watch docker changes.
# #
# # Optional
# #
# watch = true

# # Override default configuration template.
# # For advanced users :)
# #
# # Optional
# #
# # filename = "docker.tmpl"

# # Override template version
# # For advanced users :)
# #
# # Optional
# # - "1": previous template version (must be used only with older custom templates, see "filename")
# # - "2": current template version (must be used to force template version when "filename" is used)
# #
# # templateVersion = 2

# # Expose containers by default in Traefik.
# # If set to false, containers that don't have `traefik.enable=true` will be ignored.
# #
# # Optional
# # Default: true
# #
# exposedByDefault = false

# # Use the IP address from the binded port instead of the inner network one.
# # For specific use-case :)
# #
# # Optional
# # Default: false
# #
# usebindportip = true

# # Use Swarm Mode services as data provider.
# #
# # Optional
# # Default: false
# #
# swarmMode = false

# # Enable docker TLS connection.
# #
# # Optional
# #
# #  [docker.tls]
# #  ca = "/etc/ssl/ca.crt"
# #  cert = "/etc/ssl/docker.crt"
# #  key = "/etc/ssl/docker.key"
# #  insecureSkipVerify = true
