apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gopro-proxy-path
spec:
  rules:
  - http:
      paths:
      - path: /test
        backend:
          serviceName: go-server-loadbalancer
          servicePort: 8000
