kind: pipeline
type: docker
name: default

steps:
  # 測試
  - name: test
    image: golang:1.13
    commands:
      - pwd
      - ls -al
      - go fmt $(go list ./... | grep -v /vendor/)
      - go vet $(go list ./... | grep -v /vendor/)
      - go test -race $(go list ./... | grep -v /vendor/)
      - go build -o tmp
      - rm tmp

  # 發佈映像檔到 docker registry
  - name: publish
    image: docker
    commands:
      - rm -r .git
      - docker build -t registry:5000/demo:latest .
      - docker push registry:5000/demo:latest
      - docker image prune -f
    volumes:
      - name: docker
        path: /var/run/docker.sock

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
