version: '3'

services:
  web:
    image: registry:5000/myimg
    ports:
      - "8888:8888"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: fluentd:24224
        tag: httpd.access
