// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testdata/test.proto

/*
Package testdata is a generated protocol buffer package.

It is generated from these files:
	testdata/test.proto

It has these top-level messages:
	Ping
	Pong
	Enter
*/
package testdata

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Ping struct {
	Content string `protobuf:"bytes,1,opt,name=Content" json:"Content,omitempty"`
}

func (m *Ping) Reset()                    { *m = Ping{} }
func (m *Ping) String() string            { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()               {}
func (*Ping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Ping) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type Pong struct {
	Content string `protobuf:"bytes,2,opt,name=Content" json:"Content,omitempty"`
}

func (m *Pong) Reset()                    { *m = Pong{} }
func (m *Pong) String() string            { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()               {}
func (*Pong) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Pong) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type Enter struct {
	A string `protobuf:"bytes,1,opt,name=a" json:"a,omitempty"`
	P string `protobuf:"bytes,2,opt,name=p" json:"p,omitempty"`
	G int64  `protobuf:"varint,3,opt,name=g" json:"g,omitempty"`
}

func (m *Enter) Reset()                    { *m = Enter{} }
func (m *Enter) String() string            { return proto.CompactTextString(m) }
func (*Enter) ProtoMessage()               {}
func (*Enter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Enter) GetA() string {
	if m != nil {
		return m.A
	}
	return ""
}

func (m *Enter) GetP() string {
	if m != nil {
		return m.P
	}
	return ""
}

func (m *Enter) GetG() int64 {
	if m != nil {
		return m.G
	}
	return 0
}

func init() {
	proto.RegisterType((*Ping)(nil), "testdata.Ping")
	proto.RegisterType((*Pong)(nil), "testdata.Pong")
	proto.RegisterType((*Enter)(nil), "testdata.Enter")
}

func init() { proto.RegisterFile("testdata/test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x49, 0x2d, 0x2e,
	0x49, 0x49, 0x2c, 0x49, 0xd4, 0x07, 0x31, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x38, 0x60,
	0x82, 0x4a, 0x0a, 0x5c, 0x2c, 0x01, 0x99, 0x79, 0xe9, 0x42, 0x12, 0x5c, 0xec, 0xce, 0xf9, 0x79,
	0x25, 0xa9, 0x79, 0x25, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0x2e, 0x58, 0x45, 0x3e,
	0xaa, 0x0a, 0x26, 0x54, 0x15, 0x86, 0x5c, 0xac, 0xae, 0x79, 0x25, 0xa9, 0x45, 0x42, 0x3c, 0x5c,
	0x8c, 0x89, 0x50, 0xed, 0x8c, 0x89, 0x20, 0x5e, 0x01, 0x54, 0x29, 0x63, 0x01, 0x88, 0x97, 0x2e,
	0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x1c, 0xc4, 0x98, 0x9e, 0xc4, 0x06, 0x76, 0x87, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0xf5, 0x49, 0x0f, 0x3e, 0x9e, 0x00, 0x00, 0x00,
}
